### ISSUE TITLE
Cannot find module 'prettier-plugin-organize-imports'

### ISSUE THREAD

**Issue by postbird** [umijs/umi-next#831] opened 2022-06-01 03:45 UTC
- npmClient: `yarn` 
- already `yarn install` 

.pretterc
```json
{
  "singleQuote": true,
  "trailingComma": "all",
  "printWidth": 120,
  "overrides": [
    {
      "files": ".prettierrc",
      "options": { "parser": "json" }
    }
  ],
  "plugins": ["prettier-plugin-organize-imports", "prettier-plugin-packagejson"]
}
```

prettier-plugin error：

```
["INFO" - 11:42:20 AM] Formatting file:///ROOT_PATH/PROJECT_PATH/.umirc.ts
["INFO" - 11:42:20 AM] Using config file at '/ROOT_PATH/PROJECT_PATH/.prettierrc'
["INFO" - 11:42:20 AM] Using ignore file (if present) at/PROJECT_PATH/.prettierignore
["INFO" - 11:42:20 AM] File Info:
{
  "ignored": false,
  "inferredParser": "typescript"
}
["INFO" - 11:42:20 AM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 11:42:20 AM] Prettier Options:
{
  "filepath": "/ROOT_PATH/PROJECT_PATH/.umirc.ts",
  "parser": "typescript",
  "useTabs": false,
  "tabWidth": 2,
  "endOfLine": "lf",
  "singleQuote": true,
  "trailingComma": "all",
  "printWidth": 120,
  "plugins": [
    "prettier-plugin-organize-imports",
    "prettier-plugin-packagejson"
  ]
}
["ERROR" - 11:42:20 AM] Error formatting document.
["ERROR" - 11:42:20 AM] Cannot find module 'prettier-plugin-organize-imports'
Require stack:
-/PROJECT_PATH/node_modules/prettier/index.js
- /ROOT_PATH/.vscode/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
Error: Cannot find module 'prettier-plugin-organize-imports'
Require stack:
-/PROJECT_PATH/node_modules/prettier/index.js
- /ROOT_PATH/.vscode/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (node:internal/modules/cjs/loader:987:15)
	at h.resolve (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:4:761)
	at/PROJECT_PATH/node_modules/prettier/index.js:39110:25
	at Array.map (<anonymous>)
	at Object.load (/ROOT_PATH/PROJECT_PATH/node_modules/prettier/index.js:39105:65)
	at Object.load [as loadPlugins] (/ROOT_PATH/PROJECT_PATH/node_modules/prettier/index.js:15998:27)
	at/PROJECT_PATH/node_modules/prettier/index.js:39172:24
	at Object.format (/ROOT_PATH/PROJECT_PATH/node_modules/prettier/index.js:39188:12)
	at t.default.format (/ROOT_PATH/.vscode/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js:1:13489)
	at async t.PrettierEditProvider.provideEdits (/ROOT_PATH/.vscode/extensions/esbenp.prettier-vscode-9.5.0/dist/extension.js:1:10196)
	at async z.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:105121)
["INFO" - 11:42:20 AM] Formatting completed in 0.021ms.

```

**Comment by postbird** [comment] 2022-06-01 03:57
![origin_img_v2_c810a75c-0925-4521-8b6a-5bd5c04fec8g](https://user-images.githubusercontent.com/16200574/171324655-230e9a0a-6e4c-47ab-82af-dfe55fdeb62d.jpg)

**Comment by postbird** [comment] 2022-06-01 06:32
remove ` "plugins": ["prettier-plugin-organize-imports", "prettier-plugin-packagejson"]` worked for me

**Comment by fz6m** [comment] 2022-06-01 06:43
1. 你的 prettier 配置文件是如何得到的？

2. 检查你是否已经安装了 `prettier-plugin-organize-imports` 到 `package.json`

**Comment by okilled** [comment] 2022-06-02 02:58
1. pnpm umi g
2. Enable Prettier -- Enable Prettier
3. using vscode
4. Cannot find module 'prettier-plugin-organize-imports'

**Comment by fz6m** [comment] 2022-06-02 03:33
See #820

It is a vscode prettier plugin bug happens in symlink `node_modules/*` dirs.

In `yarn`: `prettier-plugin-organize-imports` will symlink to global yarn cache dir.

In `pnpm`: `prettier` will symlink to `node_modules/.pnpm/*`, vscode prettier plugin cannot find prettier plugin package raw dir.

**Currently available solutions:**

1. Waiting vscode prettier plugin fix this bug.

OR

2. Workaround prettier config : 

  ```js
  // .prettierrc
  {
    // add `./node_modules/` prefix to each plugin before
    "plugins": ["./node_modules/prettier-plugin-organize-imports"]
  }  
  ```

**Comment by PeachScript** [comment] 2022-06-03 05:38
Duplicate of #820

**Closed by PeachScript** 2022-06-03 05:38 UTC
