### ISSUE TITLE
React18.1.0 & Cannot read properties of undefined (reading 'createRoot')

### ISSUE THREAD

**Issue by 0x3Anthony** [umijs/umi-next#847] opened 2022-06-06 01:51 UTC
"@umijs/max": "^4.0.0"
Update umijs to version 4.0.0 and above, and found that the existing React18.1.0 version is no longer supported. The original default root mode of React has been changed to the createRoot style. Does umijs need to do a compatibility upgrade in this area?
<img width="727" alt="image" src="https://user-images.githubusercontent.com/100060836/172081594-3e77184e-7ff6-4a51-a77f-2b6da07ddd8a.png">

**Comment by fz6m** [comment] 2022-06-06 10:35
1.  Currently v4 version is not officially released, you should use `4.0.0-rc.21` or other with [`next`](https://www.npmjs.com/package/@umijs/max) tag version ( latest version is outdated )

2. Whether use react18  `createRoot` or react17 `render` behavior depends on the installed react version in your project.

    if the `react: "^17.0.0"` is not installed in your project's `package.json`, react18 will be used by default.

**Comment by 0x3Anthony** [comment] 2022-06-06 12:08
> 1. Currently v4 version is not officially released, you should use `4.0.0-rc.21` or other with [`next`](https://www.npmjs.com/package/@umijs/max) tag version ( latest version is outdated )
> 2. Whether use react18  `createRoot` or react17 `render` behavior depends on the installed react version in your project.
>    if the `react: "^17.0.0"` is not installed in your project's `package.json`, react18 will be used by default.

Yes, if we have been using React18 now, what else can umijs do to support it?

**Comment by sorrycc** [comment] 2022-06-07 10:20
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Closed by sorrycc** 2022-06-07 10:20 UTC
